export const INIT_GRAPH = 'INIT_GRAPH';
export const SUCCESS_SAVE_GRAPH = 'SUCCESS_SAVE_GRAPH';
export const SAVE_GRAPH = 'SAVE_GRAPH';
export const ERROR_SAVE_GRAPH = 'ERROR_SAVE_GRAPH';
export const DELETE_GRAPH = 'DELETE_GRAPH';
export const SUCCESS_DELETE_GRAPH = 'SUCCESS_DELETE_GRAPH';
export const ERROR_DELETE_GRAPH = 'ERROR_DELETE_GRAPH';
